const items =[
    {
        id: 1,
        title: 'Boozy Scoop',
        category: 'alcoholic',
        percentage: '12%',
        price: 15,
        img: './images/boozyscoop.jpg',
        desc: 'Vanilla scoop filled with rum sause and deep fried in crushed cereal.',
    },
    {
        id: 2,
        title: 'Coffee Toffee',
        category: 'non-alcoholic',
        percentage: null,
        price: 14,
        img: './images/coffeetoffee.jpg',
        desc: 'Coffee base flavor icecream with caramel toffee bites.',
    },
    {
        id: 3,
        title: 'Cookies and Cream',
        category: 'non-alcoholic',
        percentage: null,
        price: 13,
        img: './images/cookiesandcream.jpg',
        desc: 'Sweet Cream Ice Cream with pieces of Chocolate Sandwich Cookies.',
    },
    {
        id: 4,
        title: 'Ehhhhhh!',
        category: 'non-alcoholic',
        percentage: null,
        price: 16,
        img: './images/ehhhhh.jpg',
        desc: 'Maple syrup and vanilla base icecream loaded with walnuts.',
    },
    {
        id: 5,
        title: 'For the Love of Chocolate',
        category: 'alcoholic',
        percentage: '12%',
        price: 15,
        img: './images/fortheloveofchocolate.jpg',
        desc: 'Rum infused Oreoes and Belgin milk chocolate and hazelut ice cream, with a side of rum cake.',
    },
    {
        id: 6,
        title: 'Mango Swirl',
        category: 'non-alcoholic',
        percentage: null,
        price: 15,
        img: './images/mangoswirl.jpg',
        desc: 'Mango flavoured ice cream with frozen mango chunks.',
    },
    {
        id: 7,
        title: 'Mint Chocolate Chip',
        category: 'non-alcoholic',
        percentage: null,
        price: 16,
        img: './images/mintchocolatechip.jpg',
        desc: 'Mint flavoured ice cream with semi-sweet chocolate chips.',
    },
    {
        id: 8,
        title: 'Peanut Butter Swirl',
        category: 'non-alcoholic',
        percentage: null,
        price: 15,
        img: './images/peanutbutterswirl.jpg',
        desc: 'Vanilla and chocolate mix base icecream with peanut butter swirls.',
    },
    {
        id: 9,
        title: 'Pistachio',
        category: 'non-alcoholic',
        percentage: null,
        price: 16,
        img: './images/pistachio.jpg',
        desc: 'Pistachio flavoured ice cream with lightly roasted and salted pistachio nuts.',
    },
    {
        id: 10,
        title: 'Refresher Scoop',
        category: 'alcoholic',
        percentage: '10%',
        price: 15,
        img: './images/refresherscoop.jpg',
        desc: 'Peach and strawberry flavoured icecream infused with vodka and topped with frozen blueberrie.',
    },
    {
        id: 11,
        title: 'Seeing Double',
        category: 'alcoholic',
        percentage: '13%',
        price: 19,
        img: './images/seeingdouble.jpg',
        desc: 'Vanilla scoop filled with rum sause and deep fried in crushed cereal.',
    },
    {
        id: 12,
        title: 'Sex on the Beach',
        category: 'alcoholic',
        percentage: '10%',
        price: 16,
        img: './images/sexonthebeach.jpg',
        desc: 'We are bringing sexy back with a triple scoop of our almond flavoured ice cream drizzeld in caramel sauce.',
    },
    {
        id: 13,
        title: 'Smarties Fun',
        category: 'non-alcoholic',
        percentage: null,
        price: 15,
        img: './images/smartiesfun.jpg',
        desc: 'Vanilla icecream loaded and topped with smarties.',
    },
    {
        id: 14,
        title: 'Sweet Tooth',
        category: 'alcoholic',
        percentage: '11%',
        price: 15,
        img: './images/sweettooth.jpg',
        desc: 'Whiskey infused vanilla double scoop on top of our chocolate ganache.',
    },
    {
        id: 15,
        title: 'Thunder',
        category: 'alcoholic',
        percentage: '8%',
        price: 15,
        img: './images/thunder.jpg',
        desc: 'Strawberry base icecream with frozen blackcurrent bites infused with strawberry vodka.',
    },
    {
        id: 16,
        title: 'Wavy Baby',
        category: 'alcoholic',
        percentage: '10%',
        price: 14,
        img: './images/wavybaby.jpg',
        desc: 'Cotton cady scoops enfused with vodka and topped off sprinkles.',
    }
    
] 

export default items;